FROM centos:6
ENV HOME /
RUN yum update -y && yum install -y rpm-build redhat-rpm-config rpmdevtools cmake tar openssl-devel bison centos-release-scl-rh && yum install -y ruby193 ruby193-ruby-devel devtoolset-4-gcc-c++
RUN rpmdev-setuptree
RUN echo '%dist   .el6.jp3cki' >> /.rpmmacros
ADD ./rpmbuild/ /rpmbuild/
RUN chown -R root:root /rpmbuild
RUN scl enable ruby193 -- rpmbuild -ba /rpmbuild/SPECS/h2o.spec
RUN tar -czf /tmp/h2o.tar.gz -C /rpmbuild RPMS SRPMS
CMD ["/bin/true"]
