FROM rockylinux/rockylinux:10
ENV HOME /
RUN dnf distro-sync -y && \
    dnf install -y \
        autoconf \
        automake \
        bison \
        brotli-devel \
        cmake \
        gcc-c++ \
        git \
        libtool \
        make \
        openssl-devel \
        perl \
        redhat-rpm-config \
        rpm-build \
        rpmdevtools \
        ruby \
        ruby-devel \
        rubygem-rake \
        systemd-rpm-macros \
        tar \
        zlib-ng-compat-devel \
          && \
    dnf clean all && \
    rm -rf /var/cache/dnf
RUN rpmdev-setuptree
RUN echo '%dist .el10.jp3cki' >> /.rpmmacros
ADD ./rpmbuild/ /rpmbuild/
RUN chown -R root:root /rpmbuild
RUN rpmbuild -ba /rpmbuild/SPECS/h2o.spec
RUN tar -czf /tmp/h2o.tar.gz -C /rpmbuild RPMS SRPMS
CMD ["/bin/true"]
